discord.js to 14.7.1
UncleDave/DiscordSoundboardBot pull request #177
Opened 2022-12-12 20:04 UTC by stuckinab0x

Fixes #78

2022-12-12 20:54 UTC, UncleDave requested changes

2022-12-12 20:54 UTC, UncleDave commented on projects/bot/src/bot/commands/disconnect.ts
> +      connection.disconnect();
```suggestion
    getVoiceConnection(interaction.guild!.id)?.disconnect();
```

2022-12-13 02:17 UTC, stuckinab0x commented on projects/bot/src/bot/commands/disconnect.ts
> +      connection.disconnect();
The reply message relies on `connection?` as well tho so I didn't see a great way to optimize.

2022-12-13 09:41 UTC, UncleDave approved these changes

2022-12-13 09:42 UTC, merged