Add Custom Tags
UncleDave/DiscordSoundboardBot pull request #193
Opened 2023-01-03 19:40 UTC by stuckinab0x

fix #29 
fix #76

2023-01-05 05:01 UTC, stuckinab0x commented on projects/frontend/src/providers/SWRProvider.tsx
> +const value: SWRConfiguration = { revalidateOnFocus: false, fetcher: (input, init) => fetch(input, init).then(x => x.json()) };
I think the refresh token fails I was seeing miiiight have been from this sending requests in quick succession and discord rejecting a dupe or something after.

Technically this is our problem but I'll turn this off until it gets sorted, I can't think of what we do that needs to be constantly refreshing unless you want ALL users to get a new sound immediately when they tab in.

2023-01-05 05:22 UTC, stuckinab0x commented
oh we need a migration too don't we whoopsie

2023-01-14 20:01 UTC, UncleDave requested changes
Looks good to meeeeeeeeeeeeeeeeeeeeee

2023-01-14 20:02 UTC, UncleDave commented
When you fix the conflicts could you also merge dependabot's open branches into yours so we don't have to merge 6 PRs after this one?

2023-01-14 20:10 UTC, UncleDave approved these changes

2023-01-14 20:12 UTC, merged