admin panel
UncleDave/DiscordSoundboardBot pull request #211
Opened 2023-02-02 20:47 UTC by stuckinab0x

2023-02-02 20:52 UTC, stuckinab0x commented on .gitignore
> +projects/bot/sounds
This was affecting `projects/sounds`

2023-02-02 21:58 UTC, UncleDave requested changes
Not fully done yet but here's some stuff to start with. Now that we're allowing sound renaming I'm thinking we want to switch to using a sound's id in all requests that relate to a specific sound, rather than the suddenly unreliable name.

2023-02-02 21:58 UTC, UncleDave commented on projects/frontend/src/components/ButtonContainer.tsx
> +  sounds: SWRResponse<Sound[], any, any>
Moving this into a prop doesn't make a difference, SWR already dedupes requests so it's the same data in the same number of requests regardless.

2023-02-02 21:58 UTC, UncleDave commented on projects/frontend/src/components/admin-panel/AdminPanel.tsx
> +  }, []);
This is gonna call `removeEventListener()` immediately when the effect runs. It currently works (presumably) because the 2nd argument on line 136 and the 2nd argument on line 137 are not the same function, so it won't find a matching listener to remove.

```suggestion
  useEffect(() => {
    document.addEventListener('keydown', panelShortcutClose, { passive: true });
    return () => document.removeEventListener('keydown', panelShortcutClose);
  }, [panelShortcutClose]);
```

2023-02-02 21:58 UTC, UncleDave commented on projects/frontend/src/components/admin-panel/AdminPanel.tsx
> +  setShowAdminPanel: (show: boolean) => void;
This should represent an event, rather than just passing a setter function down.

```suggestion
  adminPanelClosed: () => void;
```

2023-02-02 21:58 UTC, UncleDave commented on projects/frontend/src/components/admin-panel/AdminPanel.tsx
> +  showAdminPanel: boolean;
```suggestion
  open: boolean;
```

`show` is also acceptable, but there's no need to say `AdminPanel` since this is part of `AdminPanelProps`

2023-02-02 21:58 UTC, UncleDave commented on projects/frontend/src/components/admin-panel/AdminPanel.tsx
> +  sounds: SWRResponse<Sound[], any, any>;
Same as the other comment about SWR and `sounds`

2023-02-02 21:58 UTC, UncleDave commented on projects/frontend/src/components/admin-panel/AdminPanel.tsx
> +                })}
I would grab the memoized sounds that should be shown, and just do a simple map here with no conditional shiz.

```tsx
const visibleSounds = useMemo(
  () => sounds.filter(x => x.name.toUpperCase().includes(searchTerm)),
  [sounds, searchTerm]
);
```

A `useState` + `useEffect` to keep it updated also works, but it feels like `useMemo` has it covered.

```suggestion
                { visibleSounds.map(x =>
                  return (<PanelSound key={ x.id } sound={ x } selectedSoundId={ selectedSound?.id } setSelectedSound={ setSelectedSound } previewRequest={ previewRequest } />)
                )}
```

2023-02-02 21:58 UTC, UncleDave commented on projects/web/src/routes/admin.ts
> +}
REST is for resources and generally shouldn't include actions. I'd expect the following in the sounds router:

```
GET       sounds
GET       sounds/{id}
POST      sounds/{id} - upload a sound
PUT       sounds/{id} - edit a sound, in this case only its name - admins only
DELETE    sounds/{id} - admins only
```

To control admin access I'd expect a middleware to sit in protected routes.

```ts
router.delete('/sounds/:id', isAdmin, (req, res) => {});
```

Or fuse two routers into a sounds router:

```ts
function soundsRouter(): Router {
  const unprotectedSoundsRouter = Router();

  // GET, POST

  const protectedSoundsRouter = Router();

  protectedSoundsRouter.use((req, res) => {
    // Check if the user is an admin.
  });

  // PUT, DELETE

  const mergedSoundsRouter = Router();

  mergedSoundsRouter.use('/', unprotectedSoundsRouter);
  mergedSoundsRouter.use('/', protectedSoundsRouter);

  return mergedSoundsRouter;
}
```

Disclaimer: I wrote this in the browser and have tested none of it.

2023-02-02 21:58 UTC, UncleDave commented on projects/sounds/src/sounds-service.ts
> +  }
Just try to delete it. According to the docs mongo doesn't get angery if you attempt to delete something that doesn't exist, and technically just because the sound existed when line 122 ran, doesn't mean it still exists when 124 runs.

You can check the `deletedCount` to see if you should delete the file or not.

```ts
const result = await collection.deleteOne({ name: sound.name });

if (result.deletedCount === 1) ...
```

2023-02-02 22:53 UTC, stuckinab0x commented
> Not fully done yet but here's some stuff to start with. Now that we're allowing sound renaming I'm thinking we want to switch to using a sound's id in all requests that relate to a specific sound, rather than the suddenly unreliable name.

Mkay. I agree but I stopped caring when I saw that the name was being used all the way up ¯\_(ツ)_/¯

2023-02-03 00:00 UTC, stuckinab0x commented on projects/frontend/src/components/ButtonContainer.tsx
> +  sounds: SWRResponse<Sound[], any, any>
Yeah okay, I was kinda wondering if SWR could be set up like that since you can grab `mutate`s from anywhere as well.

2023-02-03 17:24 UTC, UncleDave commented on projects/frontend/src/components/ButtonContainer.tsx
> +  sounds: SWRResponse<Sound[], any, any>
SWR is basically a fancy cache.

2023-02-09 22:40 UTC, UncleDave approved these changes

2023-02-09 22:41 UTC, merged