Frontend cleanup
UncleDave/DiscordSoundboardBot pull request #222
Opened 2023-02-14 04:30 UTC by stuckinab0x

2023-02-14 04:46 UTC, stuckinab0x commented
Lotsa CSS changes that you probably don't need to look at, soz.

Weird quirk btw, I noticed that if the `add-sound-created-at` migration runs as the seconds on your clock changes, affected sounds end up technically being two different dates and then they jump around unnecessarily when switching between `Date - New/Date - Old`. Fortunately that didn't happen when live ran.

2023-02-14 12:28 UTC, UncleDave requested changes

2023-02-14 12:28 UTC, UncleDave commented on projects/frontend/src/components/ButtonContainer.tsx
> +  return sorted.sort(compareFn);
```suggestion
  return [...soundList].sort(compareFn);
```

2023-02-14 12:28 UTC, UncleDave commented on projects/frontend/src/components/ButtonContainer.tsx
>    const soundList = [...sounds];
Don't think this is needed, every use of `soundList` in this function appears to be immutable.

2023-02-14 12:28 UTC, UncleDave commented on projects/frontend/src/components/ButtonContainer.tsx
> +    let soundList = [...sounds];
Don't think you need this if the sort functions don't mutate the array they're given.

2023-02-14 12:28 UTC, UncleDave commented on projects/frontend/src/components/SoundTile.tsx
> +const selectSoundTileMainBorder = (statusBorder: any) => {
😡 where type

2023-02-14 12:28 UTC, UncleDave commented on projects/frontend/src/contexts/custom-tags-context.ts
> +export const useCustomTagsContext = () => {
This hook can just be left as `useCustomTags` - it's not relevant that it uses a context internally. Same for sort rules. Make `CustomTagsProvider` a real component and put the logic currently in `useCustomTags` there.

2023-02-15 02:32 UTC, stuckinab0x commented on projects/frontend/src/contexts/custom-tags-context.tsx
> +  }), [showCustomTagPicker, toggleShowCustomTagPicker, disableEditTagsButton, unsavedTagged, currentlyTagging, beginTagging, toggleSoundOnTag, saveTagged]);
Are these the "right" deps to use? It's weird cuz with `SortRulesContext` if I tell it to just watch `sortRules` it seems to take care of everything.

2023-02-15 02:33 UTC, stuckinab0x commented on projects/frontend/src/contexts/sort-rules-context.tsx
> +  }), [sortRules]);
Compare with above

2023-02-16 12:36 UTC, UncleDave requested changes

2023-02-16 12:36 UTC, UncleDave commented on projects/frontend/src/contexts/custom-tags-context.tsx
> +  }), [showCustomTagPicker, toggleShowCustomTagPicker, disableEditTagsButton, unsavedTagged, currentlyTagging, beginTagging, toggleSoundOnTag, saveTagged]);
Looks right. You're building the object here and if any one of these individual properties changes you want a new object.

2023-02-16 12:36 UTC, UncleDave commented on projects/frontend/src/contexts/sort-rules-context.tsx
> +  }), [sortRules]);
It works because the things in this object change `sortRules` when they change, so it's kind of a cascadey thing. I think I'd rather be explicit with the deps here anyway and just slap em all in. When you start omitting dependencies because they're covered by the dependencies of the dependencies it gets a bit tricky to keep track of.

2023-02-16 12:36 UTC, UncleDave commented on projects/frontend/src/models/sort-rules.ts
> +  groups: (string & {}) | 'none' | 'start' | 'end';
Unsure what the deal is with `(string & {})`. If you just want to use a "it must be one of these strings" union types then just remove that first bit, unless it's doing something I'm not seeing?

```suggestion
  sortOrder: 'A-Z' | 'Date - New' | 'Date - Old';
  groups: 'none' | 'start' | 'end';
```

2023-02-16 12:36 UTC, UncleDave commented on projects/users/src/tags-service.ts
> +    await collection.updateMany({}, { $pull: { 'tags.$[].sounds': soundId } });
Can the filter specify only documents where `sounds` contains `soundId`?

2023-02-16 12:36 UTC, UncleDave commented on projects/web/src/routes/sounds.ts
> +function soundsRouter(soundsService: SoundsService, favoritesService: FavoritesService, tagService: TagsService) {
```suggestion
function soundsRouter(soundsService: SoundsService, favoritesService: FavoritesService, tagsService: TagsService) {
```

2023-02-16 12:36 UTC, UncleDave commented on projects/web/src/routes/sounds.ts
> +  router.put('/:id/:newname', isAdmin, async (req, res) => {
I'd expect newname to be in the payload instead, but probably just `{ name: string }`

2023-02-16 17:06 UTC, stuckinab0x commented on projects/frontend/src/models/sort-rules.ts
> +  groups: (string & {}) | 'none' | 'start' | 'end';
It keeps it happy when you want to assign one of them from a `string`. It makes it not for real typed but you get the nice reference/autocomplete. I probably wouldn't have bothered except the React types use it as well.

2023-02-16 18:21 UTC, UncleDave commented on projects/frontend/src/contexts/sort-rules-context.tsx
> +  }), [sortRules]);
It's fine to omit setter functions from `useState` calls that exist in _this_ function because React promises they're stable, but you shouldn't omit anything else really, even `useMemo(() => { }, [])` values because `useMemo` is an optimisation and React doesn't promise that it won't throw away the data if it wants to reclaim some memory.

2023-02-16 18:23 UTC, UncleDave commented on projects/frontend/src/models/sort-rules.ts
> +  groups: (string & {}) | 'none' | 'start' | 'end';
The solution to that is probably to make actual types here and use them everywhere.

```ts
export type SortOrder = 'A-Z' | 'Date - New' | 'Date - Old';

export interface SortRules {
  sortOrder: SortOrder;
}
```

2023-02-16 22:52 UTC, UncleDave approved these changes

2023-02-16 22:54 UTC, merged