Move web server into bot
UncleDave/DiscordSoundboardBot pull request #281
Opened 2023-05-24 01:16 UTC by stuckinab0x

2023-05-24 01:21 UTC, stuckinab0x commented
The only exciting thing about this is the `additions`/`deletions` ratio so feel free to chill on it. Maybe look at deploy/docker, application insights for stuff that I don't really touch that often.

2023-05-24 01:27 UTC, stuckinab0x commented on projects/bot/src/index.ts
> +    frontendSoundsBaseUrl: process.env.FRONTEND_SOUNDS_BASE_URL,
this is a thing cuz it's not the same for the site in dev (if you forgot cause I did 😄)

2023-05-24 08:29 UTC, UncleDave requested changes

2023-05-24 08:29 UTC, UncleDave commented on projects/bot/package.json
> +    "cors": "^2.8.5",
If we're doing the thing where the backend serves the frontend's files via proxy in dev then we shouldn't need cors at all.

2023-05-24 08:29 UTC, UncleDave commented on projects/bot/src/bot/bot.ts
I imagined the `WebServer` is probably a sibling to the `Bot` rather than being owned by it, and the `Bot` can be passed into it for it to do things like `bot.playSound()` etc.

2023-05-24 14:48 UTC, stuckinab0x commented on projects/bot/src/bot/bot.ts
This makes sense considering how few of the requests the bot interacts with.

Would you say sound/skip requests should still be events that trigger all their subscribers, or should they explicitly be `the point of this request handler is to hand its payload to bot.playSound`?

2023-05-24 15:52 UTC, UncleDave commented on projects/bot/src/bot/bot.ts
Option B pretty much. I think the web server should know about the bot and explicitly _not_ the other way around.

2023-05-26 01:14 UTC, stuckinab0x commented on projects/bot/package.json
>      "tweetnacl": "^1.0.3",
is this used?

2023-05-26 01:14 UTC, stuckinab0x commented on projects/bot/package.json
>      "@types/ws": "^8.5.4",
same whut?

2023-05-26 11:22 UTC, UncleDave commented on projects/bot/package.json
>      "tweetnacl": "^1.0.3",
That's one of those optional discord.js voice dependencies.

2023-05-26 11:25 UTC, UncleDave commented on projects/bot/package.json
>      "@types/ws": "^8.5.4",
Don't think it's used, no, take it out and see if anything gets mad?

2023-05-26 14:32 UTC, stuckinab0x commented on projects/bot/package.json
>      "@types/ws": "^8.5.4",
It's fine. Btw I removed `body-parser` as well just in case that wasn't a rando.

2023-05-26 15:34 UTC, stuckinab0x commented on projects/frontend/public/index.html
> +    <link rel="manifest" href="/site.webmanifest" crossorigin="use-credentials">
Fixes #244

2024-01-02 22:25 UTC, UncleDave approved these changes

2024-01-04 06:46 UTC, merged