Fix #6, Fix #7
UncleDave/DiscordSoundboardBot pull request #36
Opened 2022-03-08 04:30 UTC by stuckinab0x

2022-03-08 07:49 UTC, UncleDave commented
The commit message should still summarise what was done so we don't have to go digging through old issues to figure it out after this is merged. Multiline is fine, lines beyond the first are for the "extended description" if you need one, and I commonly use it for the github stuff.

> Add skip, stop commands
> Fix #6
> Fix #7

You don't need to redo the commit here, we can fix it when the PR is merged.

2022-03-08 08:17 UTC, UncleDave requested changes

2022-03-08 08:17 UTC, UncleDave commented on src/bot/commands/skip.ts
> +        const int = Number(skipOption);
Can we try to turn `skipOption` into a `Number` only once and reuse it?

2022-03-08 08:17 UTC, UncleDave commented on src/bot/commands/skip.ts
> +        else reply = `Skipped ${ skipOption } sound(s).`;
This is a good candidate to be a [ternary](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator).

```suggestion
        reply = Number(skipOption) > context.soundQueue.length
          ? All sounds skipped (count option was >= number of current sounds.)'
          : `Skipped ${ skipOption } sound(s).`
```

2022-03-08 08:17 UTC, UncleDave commented on src/bot/commands/skip.ts
> +    if (context.botAudioPlayer.player.state.status === 'idle' && context.soundQueue.length === 0) { // If player is Idle
I'd like to encapsulate more of the `AudioPlayer` related logic. If we're going to wrap it in our own `BotAudioPlayer` then I wouldn't expect to interact with the internet `AudioPlayer`, I'd rather if `BotAudioPlayer` had a `stop` method and an `isIdle` method (or maybe even a property with a getter 😱). Ideally I'd like `botAudioPlayer.player` to be `private`.

2022-03-08 08:17 UTC, UncleDave commented on src/bot/commands/skip.ts
> +        reply = 'Invalid value for count entered. Try an integer or "all" without quotes.';
Only programmers and mathematicians use `integer` on a daily basis.

```suggestion
        reply = 'Invalid value for count entered. Try a whole number or "all" without quotes.';
```

2022-03-08 16:54 UTC, stuckinab0x commented on src/bot/bot-context.ts
> +
> ESLint
Yes, all class members have COVID.

2022-03-08 17:58 UTC, UncleDave commented on src/bot/bot-context.ts
> +
Social distancing is an entirely reasonable excuse.

2022-03-09 19:23 UTC, UncleDave requested changes

2022-03-09 19:23 UTC, UncleDave commented on src/bot/commands/skip.ts
> +      return interaction.reply({ content: 'No sounds currently playing or in queue! Why not try "/sound limmy are you deaf" ? \:ear_with_hearing_aid: \:smile:', ephemeral: true });
What is ESLint whinging about here? The `\:` bits? Does discord need those?

2022-03-09 19:23 UTC, UncleDave commented on src/bot/commands/skip.ts
> +    const count = Number(skipOption);
Minor optimisation: move this down to where it's actually needed (line 32).

2022-03-09 19:23 UTC, UncleDave commented on src/bot/commands/skip.ts
> +    const skipOption = interaction.options.getString(skipCommandOption, false);
```suggestion
    const skipOption = interaction.options.getString(skipCommandOption);
```

The second parameter is optional and defaults to false so we might aswell omit it.

2022-03-09 19:51 UTC, stuckinab0x commented on src/bot/commands/skip.ts
> +      return interaction.reply({ content: 'No sounds currently playing or in queue! Why not try "/sound limmy are you deaf" ? \:ear_with_hearing_aid: \:smile:', ephemeral: true });
It's the `\` but it doesn't need them, I misread the discord.js guide. It's weird cause what it should actually have done is escaped the emoji but it's doing the same thing both ways.

We can ditch the `\`s and the ESLint comment then.

2022-03-10 07:55 UTC, UncleDave approved these changes

2022-03-10 08:22 UTC, merged