UI OAuth2 rework + frontend cleanup
UncleDave/DiscordSoundboardBot pull request #59
Opened 2022-06-17 18:39 UTC by stuckinab0x

2022-06-17 22:43 UTC, UncleDave requested changes

2022-06-17 22:43 UTC, UncleDave commented on projects/ui-server/public/app.js
> +    this.save();
`star` doesn't really need to exist, it's just an alias for `favStar` here.

```suggestion
    if (favStar.classList.contains('fav-set')) {
      favStar.innerHTML = 'star_outline';
      this.remove(favStar.parentElement.dataset.soundName);
    } else {
      favStar.innerHTML = 'star';
      this.list.push(favStar.parentElement.dataset.soundName);
    }
    favStar.classList.toggle('fav-set');
    favStar.parentElement.classList.toggle('fav');
    this.save();
```

2022-06-17 22:43 UTC, UncleDave commented on projects/ui-server/ui-client.ts
> +      client: UserData;
Don't think this name fits anymore.

2022-06-17 22:43 UTC, UncleDave commented on projects/ui-server/ui-client.ts
> +  if (req.cookies.accesstoken) userReqToken = req.cookies.accesstoken;
```suggestion
  const userReqToken = req.cookies.accesstoken;
```

The `if` doesn't look like it really does anything.

2022-06-18 01:09 UTC, stuckinab0x commented on projects/ui-server/public/app.js
> +    this.save();
it's because of `eslint(no-param-reassign)`

2022-06-18 01:14 UTC, stuckinab0x commented on projects/ui-server/ui-client.ts
> +      client: UserData;
K are you just saying change the actual property to `userdata` e.g.?

Related I was thinking about changing the filename too since the class no longer exists, though it still contains a bunch of stuff that handles a UI client's data I guess.

2022-06-18 01:25 UTC, stuckinab0x commented on projects/ui-server/ui-client.ts
> +  if (req.cookies.accesstoken) userReqToken = req.cookies.accesstoken;
Yeah it'll need to be `let` but that's fine.

I guess cookies is there but just empty, I was thinking that it would explode when a new user hit that line and you'd have to at least `req.cookies?.accesstoken`

2022-06-18 22:06 UTC, UncleDave commented on projects/ui-server/public/app.js
> +    this.save();
ech.

2022-06-18 22:07 UTC, UncleDave commented on projects/ui-server/ui-client.ts
> +      client: UserData;
> K are you just saying change the actual property to userdata e.g.?

Yus

> Related I was thinking about changing the filename too since the class no longer exists, though it still contains a bunch of stuff that handles a UI client's data I guess.

Yeah I guess it's just a collection of useful functions now, I dunno what the right name is.

2022-06-18 22:08 UTC, UncleDave commented on projects/ui-server/ui-client.ts
> +  if (req.cookies.accesstoken) userReqToken = req.cookies.accesstoken;
The assignment won't blow up unless `cookies` is null, it doesn't care if `accesstoken` is null, it'll happily assign it anyway.

2022-06-18 23:46 UTC, UncleDave approved these changes

2022-06-18 23:46 UTC, merged