+ addsound function to ui
UncleDave/DiscordSoundboardBot pull request #63
Opened 2022-07-05 18:30 UTC by stuckinab0x

2022-07-07 02:42 UTC, stuckinab0x commented
up to date, though you'll still have to tell it that the security vulnerability is okay

2022-07-07 13:18 UTC, UncleDave commented on projects/ui-server/server.ts
> +const soundsService = new SoundsService(environment.soundsConnectionString, '../bot/sounds');
The directory should come from the environment cuz it'll be something different when deployed.

2022-07-07 20:21 UTC, UncleDave requested changes

2022-07-07 20:21 UTC, UncleDave commented on projects/ui-server/server.ts
> +  }
Not all errors thrown by `addSound` mean the sound already existed; we should check if `error.message` is equal to `errors.soundAlreadyExists` imported from `botman-sounds`, if so return the 409, otherwise we don't know why it happened so just throw the error again with `throw error` and let express do what it do.

2022-07-08 00:21 UTC, stuckinab0x commented on projects/ui-server/server.ts
> +  }
Yeah np I actually started out trying to do that but I couldn't find a clean way to identify the error.

2022-07-08 01:47 UTC, stuckinab0x commented on projects/ui-server/server.ts
> +    fileName: sanitize(lowerCaseName) + extensions[validContentTypes.indexOf(req.file.mimetype)],
This matches our current situation because the `import-sounds` script made everything lower case, but do we want to do that, and if so where do we want to do it? The current `sort` rules in `sound-service`'s `find` will place anything starting with an upper case first.

2022-07-15 18:35 UTC, UncleDave commented on projects/ui-server/server.ts
> +    fileName: sanitize(lowerCaseName) + extensions[validContentTypes.indexOf(req.file.mimetype)],
I think we don't want to lowercasify anything anymore and just leave things as they're input. I'll fix the sorting in #64, and the fix I have in mind will also mean that if someone tries to upload "hello" and we already have "Hello" it'll fail.

2022-07-15 18:40 UTC, UncleDave commented on projects/ui-server/server.ts
> +    fileName: sanitize(lowerCaseName) + extensions[validContentTypes.indexOf(req.file.mimetype)],
Oh and the `import-sounds` stuff was just copy-pasted from the old `addsound` stuff, so I wouldn't pay too much attention to it.

2022-07-15 19:00 UTC, UncleDave approved these changes

2022-07-15 19:00 UTC, merged