add favorites service
UncleDave/DiscordSoundboardBot pull request #74
Opened 2022-07-24 16:38 UTC by stuckinab0x

2022-07-24 16:52 UTC, stuckinab0x commented
The alert for `/api/sound` should have popped up previously tho? CodeQL wtf bro

2022-07-25 10:38 UTC, UncleDave commented
To be as irritating as possible - now that I'm looking at it I am thinking this should be a `users` project, but it can still contain a `favoritesService` and be split up that way. But `FavoritesDocument` should be `UserDocument` etc. I would also like to see favorites being added and removed individually without having to replace the whole list.

2022-07-25 13:15 UTC, UncleDave requested changes

2022-07-25 13:15 UTC, UncleDave commented on projects/ui-server/src/public/styles.css
> +    margin: 30px 4vw 0px;
Horizontal margin is _four times_ the width of the view?

2022-07-25 13:15 UTC, UncleDave commented on projects/ui-server/src/scripts/main.js
> +    document.getElementById('body').classList.add('body-error');
Instead of putting an id on `body` you could use `document.body`.

2022-07-25 13:15 UTC, UncleDave commented on projects/ui-server/src/server.ts
> +      favorites: await favoritesService.getUserFavorites(req.cookies.userid) ?? [],
Instead of returning two string arrays you _could_ return one array of sound objects

```
{
  name: 'Sploosh',
  favorite: true
}
```

If that would be beneficial.

2022-07-25 13:15 UTC, UncleDave commented on yarn.lock
> +mongodb@^4.6.0, mongodb@^4.8.0:
Bump mongo to 4.8.0 in the new `package.json` to get rid of this change.

2022-07-25 13:15 UTC, UncleDave commented on yarn.lock
> +typescript@^4.7.2, typescript@^4.7.4:
Same.

2022-07-25 13:15 UTC, UncleDave commented on projects/favorites/package.json
> +    "build": "tsc"
Run this as part of the CI workflow, should be easy enough to figure out where to put it.

2022-07-25 16:05 UTC, stuckinab0x commented on projects/ui-server/src/public/styles.css
> +    margin: 30px 4vw 0px;
Naw this is 4% right https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units#numbers_lengths_and_percentages:~:text=px%20(pixels).-,Relative%20length%20units,-Relative%20length%20units

2022-07-25 18:52 UTC, UncleDave commented on projects/favorites/src/favorites-service.ts
> +    collection.updateOne({ userId }, { $set: { favorites: newFavorites } }, { upsert: true });
```suggestion
    await collection.updateOne({ userId }, { $set: { favorites: newFavorites } }, { upsert: true });
```

2022-07-25 19:46 UTC, stuckinab0x commented on projects/favorites/src/favorites-service.ts
> +    collection.updateOne({ userId }, { $set: { favorites: newFavorites } }, { upsert: true });
Does this behave differently or is it just because it would break if something else went after it?

2022-07-25 19:55 UTC, UncleDave commented on projects/favorites/src/favorites-service.ts
> +    collection.updateOne({ userId }, { $set: { favorites: newFavorites } }, { upsert: true });
You can await it or return it, as it is right now if you call this with `await saveUserFavorites(...)` the promise returned by `updateOne` will not be awaited, so if something goes wrong you won't be able to tell the client cuz you've already returned a 204.

2022-07-26 14:55 UTC, stuckinab0x commented
> `UserDocument` should have an `id` field instead of a `userId` field, and I'd like a unique index on that field since it's the one you've used in your `findOne`; take a look at [migrate-mongo](https://www.npmjs.com/package/migrate-mongo) to find out how to create a new migration and the [initial sounds migration](https://github.com/UncleDave/DiscordSoundboardBot/blob/master/projects/mongo/migrations/20220612194632-sounds-initial.js) for an example.

I'm a little confused about how I'm actually using these parts.

Do our migrations do anything other than run on deploy and optimize what's already there?

Also, I don't see where I'd actually use the mongo `_id` field unless you want to find users as they run through OAuth2 and send it to the frontend (I'm still gonna send their `userID` for the avatar URL tho)

2022-07-26 15:28 UTC, UncleDave commented
> UserDocument should have an id field instead of a userId field

Yeah forget that bit, `userId` is fine just so we don't have `_id` and `id`, since they will be different.

> Do our migrations do anything other than run on deploy and optimize what's already there?

You are correct. We need a migration because we want to add an index to the `userId` property. Adding the index is a one-off and then Mongo will maintain it.

In the case of users we're probably not going to use mongo's id, no, their id from auth is better.

2022-07-27 18:52 UTC, UncleDave requested changes

2022-07-27 18:52 UTC, UncleDave commented on projects/ui-server/src/scripts/main.js
>  const favorites = new Favorites();
```suggestion
new Favorites();
```

2022-07-27 18:52 UTC, UncleDave commented on projects/ui-server/src/server.ts
>  });
Use route parameters here instead of an id in the payload.

```ts
app.put('/api/favorites/:id')
```

If the client sends a request to `/api/favorites/1234` then `req.params.id` will be `1234`.

2022-07-27 18:52 UTC, UncleDave commented on projects/ui-server/src/server.ts
> +  favoritesService.addToFavorites({ userId: String(req.cookies.userid), soundId: req.body });
This isn't being awaited so the client will get a `204` regardless of what happens.

2022-07-27 18:52 UTC, UncleDave commented on projects/ui-server/src/server.ts
> +  favoritesService.removeFromFavorites({ userId: String(req.cookies.userid), soundId: req.body });
^

2022-07-27 18:52 UTC, UncleDave commented on projects/users/src/errors.ts
> +export const errors = { UserDoesNotExist: 'User does not exist' };
Should be camelcase.

2022-07-27 18:52 UTC, UncleDave commented on projects/users/src/favorites-service.ts
> +  soundId: string,
I tend to use semicolons in interfaces, but you can use anything and it doesn't produce an error cuz interfaces aren't real.

```suggestion
  userId: string;
  soundId: string;
```

2022-07-27 18:52 UTC, UncleDave commented on projects/users/src/favorites-service.ts
> +  }
I'd probably return `Promise<void>` from both of these because nothing really cares about Mongo's `UpdateResult`. Replace the two returns with awaits and it'll be happy.

2022-07-27 18:52 UTC, UncleDave commented on projects/users/src/favorites-service.ts
> +      const user = await this.getUser(userId);
Not to shit on your face after you created `UsersService` or anything, but it'd be better to pass a projection here for Mongo to use, that way it'll only send back the data we ask for.

```ts
findOne({ userId, { projection: { favorites: 1 } } })
```

2022-07-27 18:52 UTC, UncleDave commented on projects/users/src/favorites-service.ts
> +      if (error.message === 'User does not exist') return [];
The reason to put error messages in `errors.ts` is so we can use them for comparison and not have to worry about typos or future changes.

```suggestion
      if (error.message === errors.userDoesNotExist) return [];
```

2022-07-27 18:52 UTC, UncleDave commented on projects/users/src/users-service.ts
> +  private static usersCollection: Promise<Collection<UserDocument>>;
We're doing the static stuff in `MongoService` because we don't want multiple connections to the database from one application, but referencing a collection in multiple places won't create more connections, so we don't really need this.

2022-07-27 21:45 UTC, stuckinab0x commented on projects/users/src/favorites-service.ts
> +      if (error.message === 'User does not exist') return [];
Oh yeah this what I was talking about but I didn't think to just use the reference here too

2022-07-28 07:02 UTC, UncleDave commented on projects/users/src/favorites-service.ts
> +  soundId: string,
It lets them through because interfaces are a TypeScript thing, so they don't get compiled to JavaScript, they're just there for type checking.

2022-07-28 07:06 UTC, stuckinab0x commented on projects/users/src/users-service.ts
> +  private static usersCollection: Promise<Collection<UserDocument>>;
you talked about doing this tho >:|

2022-07-28 07:22 UTC, stuckinab0x commented on projects/users/src/favorites-service.ts
> +  soundId: string,
yeah I know that part but usually eslint will yell

2022-07-28 07:24 UTC, UncleDave commented on projects/users/src/users-service.ts
> +  private static usersCollection: Promise<Collection<UserDocument>>;
For the mango connection, we don't need to do it for collections though. You can still inherit it and what not but I don't think it needs to be static.

2022-07-28 18:17 UTC, UncleDave requested changes

2022-07-28 18:17 UTC, UncleDave commented on projects/users/src/favorites-service.ts
>      }
Son, you're now throwing an error and catching it in the same method.

```ts
const collection = await this.usersCollection;
const user = await collection.findOne({ userId }, { projection: { favorites: 1 } });

return user?.favorites ?? [];
```

2022-07-28 20:53 UTC, stuckinab0x commented on projects/ui-server/src/scripts/favorites.js
> +  },
yikes

2022-07-29 08:17 UTC, UncleDave approved these changes

2022-07-29 08:18 UTC, UncleDave commented
I'll merge this later once I've fixed the config on live.

2022-07-29 14:35 UTC, UncleDave requested changes

2022-07-29 14:35 UTC, UncleDave commented on projects/users/src/favorites-service.ts
> +    await collection.updateOne({ userId: options.userId }, { $push: { favorites: options.soundId } }, { upsert: true });
Use `$addToSet` rather than `$push`, as it won't allow a duplicate key to be added to the array.

```suggestion
    await collection.updateOne({ userId: options.userId }, { $addToSet: { favorites: options.soundId } }, { upsert: true });
```

2022-07-29 17:19 UTC, UncleDave approved these changes

2022-07-29 17:24 UTC, merged